name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Clone Repo
      run: |
        export LATEST_APP=$(wget -qO- https://api.github.com/repos/Deeptrain-Community/chatnio/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
        git clone -b $LATEST_APP https://github.com/Deeptrain-Community/chatnio
        npm install -g pnpm

    - name: Build Frontend
      run: |
        cd chatnio/app
        pnpm install && \
        pnpm run build && \
        rm -rf node_modules src
        cd ../..

    - name: Build binaries
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y wget curl git gcc bash gawk gsed llvm
          wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz && rm go1.22.0.freebsd-amd64.tar.gz
          ln -s /usr/local/go/bin/go /usr/local/bin/go
        run: |
          cd chatnio
          go install
          GO111MODULE=on CGO_ENABLED=1 go build -ldflags '-extldflags "-static"' -o chatnio -buildvcs=false
          mkdir -p ../target
          mkdir -p ../target/app
          cp chatnio ../target/chatnio
          cp -R app/dist ../target/app/dist
          cd ../target && tar -czf ../chatnio-freebsd-amd64.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: chatnio-freebsd-amd64
        path: |
            chatnio-freebsd-amd64.tar.gz

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/Deeptrain-Community/chatnio/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              chatnio-freebsd-amd64.tar.gz
   
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
